services:
    
    blog_db:
        image: postgres:17
        ports: [8080:5432]
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=social_website
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./db_data:/var/lib/postgresql/data